version: '3'
services:
    pg_container:
        image: postgres:9.6
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: prisma
            POSTGRES_PASSWORD: prisma
        volumes:
            - pg_volume:/var/lib/postgresql/troup
volumes:
    pg_volume:
